export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';

export const LOGOUT = 'LOGOUT';

export const LIST_SHOPS = 'LIST_SHOPS';
export const ERROR_SHOPS = 'ERROR_SHOPS';
export const GET_SHOP = 'GET_SHOP';
export const CREATE_SHOP = 'CREATE_SHOP';
export const NEW_SHOP_ERROR = 'NEW_SHOP_ERROR';

export const OWNER_SHOPS = 'OWNER_SHOPS';
export const OWNER_SHOPS_ERROR = 'OWNER_SHOPS_ERROR';

export const UPDATE_SHOP = 'UPDATE_SHOP';
export const UPDATE_SHOP_ERROR = 'UPDATE_SHOP_ERROR';
export const DELETE_SHOP = 'DELETE_SHOP';
export const DELETE_SHOP_ERROR = 'DELETE_SHOP_ERROR';

export const GET_PRODUCT = 'GET_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR';
export const LIST_PRODUCT_BY_SHOP = 'LIST_PRODUCT_BY_SHOP';
export const LIST_PRODUCT_BY_SHOP_ERR = 'LIST_PRODUCT_BY_SHOP_ERR';

export const LIST_RELATED = 'LIST_RELATED';
export const LIST_RELATED_ERROR = 'LIST_RELATED_ERROR';

export const LIST_LATEST = 'LIST_LATEST';
export const LIST_LATEST_ERROR = 'LIST_LATEST_ERROR';

export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const LIST_CATEGORIES_ERROR = 'LIST_CATEGORIES_ERROR';

export const LIST_SEARCH = 'LIST_SEARCH';

export const LIST_RESULT = 'LIST_RESULT';
export const LIST_RESULT_ERROR = 'LIST_RESULT_ERROR';
